### ISSUE TITLE
Unexpected key(s) in state_dict: "decoder.output_projection.weight"

### ISSUE THREAD

**Issue by ludicrous0104** [cl-tohoku/ILYS-aoba-chatbot#1]
5aa09ce を取得して、手順書通りに対話を実行しようとしたところ、
python run.py --model ilys_aoba_transformer_finetuned.pt --spm spm_10M_tweets.cr9999.bpe.32000.model --vocab ilys_aoba_transformer_vocab.zip

を実行した後にしばらくして以下のようなエラーが出力されて実行できませんでした。

| [context] dictionary: 32001 types
| [response] dictionary: 32001 types
| [context] dictionary: 32001 types
| [response] dictionary: 32001 types
Traceback (most recent call last):
  File "run.py", line 38, in <module>
    main()
  File "run.py", line 24, in main
    model = NeuralDialogueModel(args)
  File "/home/lamuda/pyproj/ILYS/ILYS-aoba-chatbot/neural_dialogue_model/models.py", line 32, in __init__
    self.models = self._load_models(self.args)
  File "/home/lamuda/pyproj/ILYS/ILYS-aoba-chatbot/neural_dialogue_model/models.py", line 158, in _load_models
    model.load_state_dict(state["model"], strict=True, args=state["args"])
  File "/home/lamuda/pyproj/ILYS/venv/lib/python3.8/site-packages/fairseq/models/fairseq_model.py", line 71, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/lamuda/pyproj/ILYS/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 846, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Unexpected key(s) in state_dict: "decoder.output_projection.weight". 

環境は以下の通りです
python 3.8.6
fairseq           0.9.0
numpy             1.19.4
sentencepiece     0.1.91
torch             1.5.1
torchvision       0.6.1

**Comment by rk-fujifuji** [comment]
ご報告ありがとうございます．
fairseqをこのリポジトリからインストールしていただけると正常に動くかと思います．

インストールの手順は以下の通りです．
```
cd ILYS-aoba-chatbot/fairseq
pip install --editable .
```
fairseqのインストールについて説明不足で申し訳ありませんでした．
合わせてREADMEも更新させていただきました．
